services:
  golendar:
    build: .
    environment:
      TZ: America/Sao_Paulo
      TELEGRAM_BOT: "your_bot_token"
      TELEGRAM_CHAT_ID: "your_chat_id"
      SONARR_URL: "sonarr_url" #Default: http://localhost:8989
      SONARR_API_KEY: "sonarr_api_key"
      RADARR_URL: "radarr_url" #Default: http://localhost:7878
      RADARR_API_KEY: "radarr_api_key"
    restart: unless-stopped
    container_name: golendar
