services:
  golendar:
    build: .
    environment:
      TZ: America/Sao_Paulo
      TELEGRAM_BOT: ""
      TELEGRAM_CHAT_ID: ""
      SONARR_URL: "" #Default: http://localhost:8989
      SONARR_API_KEY: ""
      RADARR_URL: "" #Default: http://localhost:7878
      RADARR_API_KEY: ""
    restart: unless-stopped
    container_name: golendar
